### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by kurkle** [kurkle/chartjs-plugin-autocolors#21]

**Comment by Quocnamit** [comment]
is there any update on this ?

**Comment by kurkle** [comment]
> is there any update on this ?

No updates. I'll get to this, when I have some spare time. Can take a while. Pull requests are always welcome.

**Comment by kurkle** [comment]
added in 43f1b6d3c0847354cf0fac08f824ca7f3daa3ebc
