### ISSUE TITLE
given colors as option?

### ISSUE THREAD

**Issue by Rello** [kurkle/chartjs-plugin-autocolors#3]
Hello,

thank you for your plugin! this is my only chance I found to get colors into chartjs since v3.

before I was using [colorschemes](https://github.com/nagix/chartjs-plugin-colorschemes) because you could choose which direction of colors you want.
But I don´t understand their code and never got it working in v3.

Do you thing about enhancing your app so serve as a basis to also inject a predefined set of colors into the chart as an additional option? what do you think?

```
plugins: {
      autocolors: {
        colors: ["#767f8b", "#b3b7b8", "#5c6068", "#d3d3d3", "#989ca3"]
      }
    }
```

**Comment by kurkle** [comment]
I think that can be handled without any plugin already:
```js
new Chart('id', {
  type: 'bar',
  data: (...),
  options: {
    backgroundColor: ["#767f8b", "#b3b7b8", "#5c6068", "#d3d3d3", "#989ca3"],
    borderColor: ["#767f8b", "#b3b7b8", "#5c6068", "#d3d3d3", "#989ca3"]
  }
}
```

**Comment by Rello** [comment]
🤯

let me check. thank you ☺️

**Comment by Rello** [comment]
it works. thank you!
So I am in between using the simple way vs your nice work 😎

Lines are good. will set the tick colors the same.
just the bars are all changing, but thats an issue on my side...
![Bildschirmfoto 2021-04-15 um 08 24 27](https://user-images.githubusercontent.com/13385119/114823581-ff291c80-9dc3-11eb-9ba3-6c40c8d4e055.png)

**Comment by Rello** [comment]
I had to solve the bar-issue by defining the color (using an index to a given color array) directly when creating the datasets.
but thank you for showing me the right direction!
